### ISSUE TITLE
Kernel 2.6 2.7

### ISSUE THREAD

**Issue by frusswur** [codelion/pathgrind#3]
Hi, 
I tried to build this, but the configure step says it only works with Kernel 2.6 or 2.7. Is there any reason for this?

**Comment by codelion** [comment]
It has only been tested on those Kernel versions. There may be some incompatibilities with new versions as it is based on an old version of valgrind.

**Comment by frusswur** [comment]
I wrote a Vagrantfile to automate the installation process of Fuzzgrind on Ubuntu Server 10.04 32-Bit with kernel 2.6.

**Comment by codelion** [comment]
Great work, I am sure it will be helpful for other users as well. Can you please submit a PR?

**Comment by frusswur** [comment]
I use a Base-Box from Atlas. It should be enough to execute vagrant up.
[Vagrant_Fuzzgrind.zip](https://github.com/codelion/pathgrind/files/343302/Vagrant_Fuzzgrind.zip)

I can run Fuzzgrind with the examples now. But how can I analyze other Binaries? Is there any tutorial for this tool?

**Comment by codelion** [comment]
There is no tutorial as such but the following blog post may give you some idea - https://blog.sourceclear.com/dynamic-symbolic-execution-with-pathgrind/

**Comment by codelion** [comment]
Thanks for contributing the vagrant script I added it to the main repo.
