### ISSUE TITLE
configuration error: please use gcc >= 3.0 or clang >= 2.9

### ISSUE THREAD

**Issue by ksloven** [codelion/pathgrind#4]
Good day,
I'm trying to get pathgrind to work on my machine but I keep getting the "configuration error: please use gcc >= 3.0 or clang >= 2.9" error even though I have installed version greater than the ones required.

Has anyone come across this and how did you fix it?

thanks

**Comment by codelion** [comment]
What is the configuration of your machine? May be you can try the vagrant setup first and see if it works.

**Comment by ksloven** [comment]
I tried the vagrant set up too (using the installFuzzgrind.sh) and i still get the same error.
I'm on Linux 4.8.0-36-generic 16.04.1 i686 GNU/Linux.

**Comment by codelion** [comment]
I tried it again and cannot reproduce this error. With the vagrant set up you only need to go to the vagrant-setup folder and do `vagrant up` then you can use `vagrant ssh` to login to the machine and run a fuzzing session.

**Comment by codelion** [comment]
Seems like this error comes when compiling valgrind directly with non standard gcc, you can try fixing the configuration as suggested here - http://valgrind.10908.n7.nabble.com/Compiling-valgrind-with-non-default-gcc-td42871.html

**Comment by encrypted-soul** [comment]
@codelion I am currently stuck with the same error. Could you please tell me how this problem was resolved? The link you are providing seems to have been taken down.

**Comment by codelion** [comment]
@gagan-aryan the link is available via way back machine - https://web.archive.org/web/20190730141826/http://valgrind.10908.n7.nabble.com/Compiling-valgrind-with-non-default-gcc-td42871.html

**Comment by encrypted-soul** [comment]
@codelion Thanks a lot! That was helpful. I am now stuck in some other errors while running `make install` command. It would be great if you could tell me how I can proceed about resolving this. 
![Screenshot from 2020-11-07 03-45-41](https://user-images.githubusercontent.com/62807661/98419771-c44fe980-20ab-11eb-911c-d8966ab52623.png)
